# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/kyocera/C5155/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/kyocera/C5155/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/kyocera/C5155/proprietary/lib/libnv.so:obj/lib/libnv.so \

PRODUCT_COPY_FILES += \
    vendor/kyocera/C5155/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/kyocera/C5155/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/kyocera/C5155/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/kyocera/C5155/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/kyocera/C5155/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/kyocera/C5155/proprietary/bin/rild:system/bin/rild \
    vendor/kyocera/C5155/proprietary/bin/thermald:system/bin/thermald \
    vendor/kyocera/C5155/proprietary/bin/hdmid:system/bin/hdmid \
    vendor/kyocera/C5155/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/kyocera/C5155/proprietary/bin/cnd:system/bin/cnd \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxQcelpHw-test:system/bin/mm-adec-omxQcelpHw-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxaac-test:system/bin/mm-adec-omxaac-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxadpcm-test:system/bin/mm-adec-omxadpcm-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxamr-test:system/bin/mm-adec-omxamr-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxamrwb-test:system/bin/mm-adec-omxamrwb-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxmp3-test:system/bin/mm-adec-omxmp3-test \
    vendor/kyocera/C5155/proprietary/bin/mm-adec-omxvam-test:system/bin/mm-adec-omxvam-test \
    vendor/kyocera/C5155/proprietary/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \
    vendor/kyocera/C5155/proprietary/bin/mm-aenc-omxamr-test:system/bin/mm-aenc-omxamr-test \
    vendor/kyocera/C5155/proprietary/bin/mm-aenc-omxevrc-test:system/bin/mm-aenc-omxevrc-test \
    vendor/kyocera/C5155/proprietary/bin/mm-aenc-omxqcelp13-test:system/bin/mm-aenc-omxqcelp13-test \
    vendor/kyocera/C5155/proprietary/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
    vendor/kyocera/C5155/proprietary/bin/mm-audio-ctrl-test:system/bin/mm-audio-ctrl-test \
    vendor/kyocera/C5155/proprietary/bin/mm-audio-mvs-test:system/bin/mm-audio-mvs-test \
    vendor/kyocera/C5155/proprietary/bin/mm-audio-native-test:system/bin/mm-audio-native-test \
    vendor/kyocera/C5155/proprietary/bin/mm-audio-voem_if-test:system/bin/mm-audio-voem_if-test \
    vendor/kyocera/C5155/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/kyocera/C5155/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/kyocera/C5155/proprietary/bin/mm-jps-enc-test:system/bin/mm-jps-enc-test \
    vendor/kyocera/C5155/proprietary/bin/mm-mpo-dec-test:system/bin/mm-mpo-dec-test \
    vendor/kyocera/C5155/proprietary/bin/mm-mpo-enc-test:system/bin/mm-mpo-enc-test \
    vendor/kyocera/C5155/proprietary/bin/mm-omx-devmgr:system/bin/mm-omx-devmgr \
    vendor/kyocera/C5155/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/kyocera/C5155/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/kyocera/C5155/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    vendor/kyocera/C5155/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/kyocera/C5155/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    vendor/kyocera/C5155/proprietary/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    vendor/kyocera/C5155/proprietary/bin/mm-video-driver-test:system/bin/mm-video-driver-test \
    vendor/kyocera/C5155/proprietary/bin/mm-video-encdrv-test:system/bin/mm-video-encdrv-test \
    vendor/kyocera/C5155/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/kyocera/C5155/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/kyocera/C5155/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/kyocera/C5155/proprietary/lib/hw/sensors.C5155.so:system/lib/hw/sensors.C5155.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxVdec.so:system/lib/libOmxVdec.so \
    vendor/kyocera/C5155/proprietary/lib/libOmxVenc.so:system/lib/libOmxVenc.so \
    vendor/kyocera/C5155/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    vendor/kyocera/C5155/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/kyocera/C5155/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/kyocera/C5155/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/kyocera/C5155/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/kyocera/C5155/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/kyocera/C5155/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/kyocera/C5155/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/kyocera/C5155/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/kyocera/C5155/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/kyocera/C5155/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/kyocera/C5155/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/kyocera/C5155/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/kyocera/C5155/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/kyocera/C5155/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/kyocera/C5155/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/kyocera/C5155/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/kyocera/C5155/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/kyocera/C5155/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/kyocera/C5155/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/kyocera/C5155/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/kyocera/C5155/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/kyocera/C5155/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/kyocera/C5155/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/kyocera/C5155/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/kyocera/C5155/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/kyocera/C5155/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/kyocera/C5155/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/kyocera/C5155/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/kyocera/C5155/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/kyocera/C5155/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/kyocera/C5155/proprietary/lib/libpdapi.so:system/lib/libpdapi.so \
    vendor/kyocera/C5155/proprietary/lib/libpdsm_atl.so:system/lib/libpdsm_atl.so \
    vendor/kyocera/C5155/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/kyocera/C5155/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/kyocera/C5155/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/kyocera/C5155/proprietary/lib/librpc.so:system/lib/librpc.so
